### PR TITLE
chore: Update firestore dependency version

### PR DESCRIPTION
**Pull request by percula**
This enables compatibility with the latest version of Firestore.

### CODE REVIEW

**Comment by percula** [comment]
This solves #13

**Comment by mirdones** [comment]
Now we just need to know when the developers will make a new release.

**Comment by zoro238** [comment]
Has been updated and terminated with the latest issues of firestore 18.0.1

**Comment by KelvinPac** [comment]
Am getting the same error in 18.2.0. Was it a temporary fix and do we expect patches for every new version?

**Pull request merged**
